server.js

Some updates

---

.travis.yml

Adds .travis.yml file

---

.travis.yml

Slack notification

---

README.md

Adds status image for CI build

---

Dockerfile
docker-compose.yml

Initial docker crap and shit

---

Dockerfile
docker-compose.yml
package.json
server.js

- Adds logger to server.js
- Updates docker-compose
- Updates Dockerfile for dev env
- Adds nodemon

Some updates and shit

---

app/lib/render.js
app/views/home.html
app/views/layout.html
features/home_page.feature
package.json
public/css/main.css
server.js

Some layouts

---

app/views/home.html
app/views/layout.html
app/views/question.html
features/home_page.feature
features/question_page.feature
features/step_definitions/main_step.js
features/step_definitions/question_step.js
server.js

- add test to check the page title for homepage
- add test for question page

add question routes

---

Dockerfile

Some Dockerfile fix

---

Makefile
server.js

Fixes dockerized test

---

README.md
app/views/partials/header.html
app/views/question.html
app/views/register.html
features/question_page.feature
features/register.feature
features/step_definitions/main_step.js
features/step_definitions/question_step.js
features/step_definitions/register_step.js
server.js

* Update README.md
* Update Question page
* Implement Registration page

Update Question and implement registration page

---

Makefile
docker-compose.yml

- Adds `compose` tasks in Makefile
- Also added `sandwitch` which is a wrapper to `compose`
just for fun.
- Updates compose file to use unified password

Setup some env vars for linked containers

---

Makefile
README.md

Minor typo fixes and some README updates

---

Makefile
scripts/compose.sh

- Adds `scripts/compose.sh` script
- Updates make sandwich task implementation

Fixes `make sandwich` task

---

.eslintrc
app/lib/render.js
app/routes/home.js
features/step_definitions/main_step.js
features/support/world.js

Fixes eslint errors from JS files

---

.eslintignore

Updates .eslintignore

---

docker-compose.yml

Wrong spelling kudasai!

---

.gitignore
app/routes/home.js
docker-compose.yml
server.js

Should fix mongodb issue

---

Makefile
README.md
docker-compose.yml
server.js

More docker-related updates

---

Dockerfile

Use node:argon instead of 5.x

---

app/routes/home.js
app/routes/index.js
features/home_page.feature
server.js

So basically, every files inside the `routes`
folder excluding `index.js` and non-js files
will be automatically required and added it's
method, path and handler property to the main
`router`.
Note: Please see `home.js` for config example.
- [WIP] baking something awesome...
COMING SOON!

Route handler/bootstraper - Bootstrap route handlers inside `routes` folder

---

app/views/home.html
app/views/layout.html
app/views/partials/footer.html
app/views/partials/header.html
features/home_page.feature
public/css/main.css

Mdae some ui changes

---

app/views/home.html
app/views/partials/header.html
public/css/main.css

some ui updates

---

app/routes/home.js
app/routes/index.js

updates route implementation

---

.gitignore
.travis.yml
app/models/schema/user.js
app/routes/auth.js
app/routes/home.js
app/views/home.html
app/views/partials/header.html
package.json
server.js

This is just an initial implementation
mga dodong. Please lang ko ninyo, if
naa mo time i refactor.
:+1:

FB LOGIN with grant and purest

---

app/routes/home.js
app/routes/question.js
app/views/home.html

CSRF et al

---

app/views/home.html
app/views/partials/header.html
config/app.json
config/fileserver.json
config/grant.json
features/home_page.feature
server.js

- Mostly ui changes
- Use config based setups
- And more awesomeness!

Refactors some shit

---

app/lib/notfound.js
app/routes/auth.js
app/routes/home.js
app/views/error.html
app/views/home.html
app/views/partials/header.html
config/app.json
config/fileserver.json
docker-compose.yml
package.json
server.js

Docker specific configs and env

---

server.js

Tidy up server.js

---

app/views/home.html
public/css/main.css

Some UI Changes

---

app/routes/auth.js

This properly handles login from
FB.
Please review and merge mga dodong.
CC @technowar, @xanderdwyl

Fixes login issue

---

app/models/schema/user.js
app/routes/auth.js

Modified fb query to include additional
profile data if available such as:
- picture
- email

User and auth updates

---

app/routes/home.js
app/views/partials/header.html
public/css/main.css

Minor UI changes

---

app/views/home.html
public/css/main.css

ui updates desu!

---

app/routes/home.js
app/views/partials/header.html
app/views/profile.html
public/css/main.css

Initial profile page

---

app/models/schema/user.js
app/routes/admin.js
app/routes/auth.js
app/views/admin.html
app/views/home.html
app/views/layout.html
app/views/questions.html
features/admin_page.feature
features/home_page.feature
features/step_definitions/main_step.js

- add new routes for admin and admin/questions
- modify user model and add role fields
- add test for admin page
Signed-off-by: Alexjander Bacalso <janderbacalso@gmail.com>

implement admin routes

---

app/models/index.js
app/models/schema/answer.js
app/models/schema/base.js
app/models/schema/user.js

Initial structures for models etc...
let me know if you have questions
about them
(╯°□°）╯︵ ┻━┻

Models et al

---

app/routes/admin.js
app/routes/home.js
app/routes/question.js
app/views/home.html
app/views/question.html
app/views/questions.html

- create route to answer question
- display answered questions in home page
- display unanswered questions in admin page
Signed-off-by: Alexjander Bacalso <janderbacalso@gmail.com>

implement to answer the list questions
